name: testing

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install panflute pylatexenc

    - name: Install dependencies-pandocmath
      run: |
        sudo wget https://github.com/jgm/pandoc/releases/download/3.1.6.1/pandoc-3.1.6.1-1-amd64.deb
        sudo dpkg -i pandoc-3.1.6.1-1-amd64.deb

    - name: Test with pytest
      run: |
        pip install pytest pytest-cov
        pytest tests/tests.py --doctest-modules --junitxml=tests/junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
