name: testing

on: [push]

jobs:
  build:

    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install package
      run: pip install -e .

    - name: Install dependencies-pandocmath
      run: |
         if [ "$RUNNER_OS" == "Linux" ]; then
              sudo wget --quiet https://github.com/jgm/pandoc/releases/download/3.1.6.1/pandoc-3.1.6.1-1-amd64.deb
              sudo dpkg -i pandoc-3.1.6.1-1-amd64.deb
         elif [ "$RUNNER_OS" == "Windows" ]; then
              choco install pandoc
         else
              echo "$RUNNER_OS not supported"
              exit 1
         fi
      shell: bash

    - name: Test with pytest
      run: pytest tests --doctest-modules
